config/routes.rb
Batman2::Application.routes.draw do
  root to: 'batmobile#home'
  match '/more', to:'batmobile#about'
  match '/do_stuff', to: 'batmobile#do_stuff'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/batmobile_controller.rb
class BatmobileController < ApplicationController
  def home
  end

  def about
  end

  def do_stuff
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batmobile_helper.rb
module BatmobileHelper
end

app/views/batmobile/about.html.erb
<%provide(:title, "More")%>
<h1>Hey, you</h1>
<h2>I love you and you're awesome</h2>
<p align="center">I honestly can no longer remember what life felt like before you. Whenever I try to I get sad, so I stop doing that.<br> Your smile makes me instantly happy. I don't really understand that.<br>
<p2 align="center"> (like biologically. it's just weird)</p2><br>
I love holding hands with you in public places. I like to see people seeing you being with me.<br>
I never cease to be impressed by you. Lately, it's specifically been the way you handle yourself in a conversation. You have this strangely powerful energy that I can't really put my finger on. I like that. It's one of the reasons I don't just like you, I respect you. But also, I like you. Which is cool.<br>
<img src="alex_snow.jpg" width="300"/><br>
<p2>whenever i'm sad, i look at this picture and then i'm not sad<p2>
</p>

app/views/batmobile/do_stuff.html.erb
<% provide(:title, 'Even more')%>
<h1>Stuff</h1>
<h2>particularly, stuff that we should do</h2>
<div align="center">
	<div style="background-color:#f0f0f0;width:400px" align="left">
		<p>
			<ul>
				<li>rock climbing</li>
				<li>take fun pictures</li>
				<li>play monopoly at IKEA</li>
				<li>swim until we are about to drown, but then we don't</li>
			</ul>
		</p>
	</div>
</div>

app/views/batmobile/home.html.erb
<% provide(:title, 'HOME')%>
<h1>Ode to Alex Fraley</h1>
<h2>some men write love songs. some men write poems. i write code.<br>feel the love</h2>
<p align="middle">
<img src="IMG_6765.JPG" alt="rss feed" width="800" align = "middle"/>
<br>
let the cascading style sheets cascade a river of adoration into your heart
</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "alex","#",id: "logo"%>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path%></li>
					<li><%= link_to "More", more_path%></li>
					<li><%= link_to "Even more", do_stuff_path%></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%=yield(:title)%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class='container'>
		<%=yield%>
	</div>
</body>
</html>

app/views/layouts/header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "alex","#",id: "logo"%>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path%></li>
					<li><%= link_to "More", more_path%></li>
					<li><%= link_to "Even more", do_stuff_path%></li>
				</ul>
			</nav>
		</div>
	</div>
</header>